---

- name: Install Apache server and relevant dependecies
  apt: 
    state: present 
    update_cache: yes
    name:
      - apache2
      - libapache2-mod-wsgi
            
- name: ensure module wsgi is enables
  apache2_module:
    name: wsgi
    state: present
  notify: 
    - restart apache2
          
- name: de-activate the default apache2 site
  file: 
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: 
    - restart apache2
          
- name: ensure web server started
  service:
    name: apache2
    state: started
    enabled: yes